#!/usr/bin/python

import sys
import subprocess
import urllib
import urlparse

args = sys.argv
url = urlparse.urlparse(args[-1])

query = urlparse.parse_qs(url.query, True)
query_c = dict(query)
params = {}

for (key, value) in query.items():
  if key.startswith("_"):
    del query_c[key]
    params[key[1:]] = value[0]

url = url._replace(query=urllib.urlencode(query_c))
args[-1] = url.geturl()

for (key, value) in params.items():
  if key == 'win':
    x1, y1, x2, y2 = (float(v) for v in value.split(','))
    w, h = (int(v) for v in subprocess.Popen('DISPLAY=:0 xrandr | grep "\*" | cut -d" " -f4',shell=True,stdout=subprocess.PIPE,stderr=file('/dev/null','wa')).communicate()[0].strip().split('\n')[0].split('x'))
    value = ','.join(str(int(round(v))) for v in [x1*w, y1*h, x2*w, y2*h])

  args.insert(1, '--'+key+'='+value)

args[0] = '/usr/bin/omxplayer'
subprocess.call(args)
